[loggers]
keys=root,filleLogger,consoleLogger

[handlers]
keys=filleHandler,consoleHandler

[formatters]
keys=filleFormatter,consoleFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler,filleHandler

[logger_filleLogger]
level=DEBUG
handlers=filleHandler
qualname=filleLogger
propagate=0

[logger_consoleLogger]
level=INFO
handlers=consoleHandler
qualname=consoleLogger
propagate=0

[handler_filleHandler]
class=FileHandler
level=DEBUG
formatter=filleFormatter
args=('log/log.log', 'w')

[handler_consoleHandler]
class=StreamHandler
formatter=consoleFormatter
args=(sys.stdout,)

[formatter_filleFormatter]
format=%(asctime)s,%(levelname)s,%(name)s,%(message)s

[formatter_consoleFormatter]
format=[%(name)s] %(levelname)s: - %(message)s